#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
chown -R ubuntu:ubuntu ${CURRENT_DIR}
source ${SOURCE_DIR}/base/deploy
if [ -f ${CURRENT_DIR}/context.xml  ]; then
	cp -f ${CURRENT_DIR}/context.xml /etc/tomcat7/context.xml
fi

if [ -d ${CURRENT_DIR}/dependencies ]; then
	cp -f ${CURRENT_DIR}/dependencies/* /usr/share/tomcat7/lib/
fi

${VENV_DIR}/bin/python ${SOURCE_DIR}/hooks.py
